apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: waas-mvp
spec:
  title: WaaS MVP
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Tanzu-Solutions-Engineering/WaaS-MVP
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/Tanzu-Solutions-Engineering/WaaS-MVP
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
