#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if hasattr(data, "values") and hasattr(data.values, "password"):
#@overlay/match by=overlay.subset({"kind": "TrainingPortal", "metadata": {"name": "waas-mvp"}}), expects="1+"
---
spec:
  #@overlay/match missing_ok=True
  portal:
    password: #@ data.values.password
#@ end